### ISSUE TITLE
DBMS data diagnosis function supports group_by()

### ISSUE THREAD

**Issue by choonghyunryu** [choonghyunryu/dlookr#93]
### Task

- Add group_by() support functions
   - [x] diagnose.tbl_dbi()
   - [x] diagnose_category.tbl_dbi()
   - [x] diagnose_numeric.tbl_dbi()
   - [x] diagnose_outlier.tbl_dbi()

**Comment by choonghyunryu** [comment]
I implemented on github development version 0.6.2.9001.
